### ISSUE TITLE
spec file has extra apostrophe, causing tests to not run

### ISSUE THREAD

**Issue by agdavid** [learn-co-students/sinatra-password-security-v-000#91]
Hi LV team, I ran the "learn" command for the rspec tests and they did not run correctly.  In the file spec/create_users_migration_spec.rb, the first line of code (rb: 1) is as follows:  `require_relative '../db/migrate/20150916154312_create_users.rb''`

I deleted the last apostrophe and it worked.  The revised rb:1 would read:
`require_relative '../db/migrate/20150916154312_create_users.rb'`

Let me know what you think! 

Best,
Antonio

**Comment by mystycs** [comment]
Agreed, i had to delete the extra ' to make it work.

**Comment by gj** [comment]
@pletcher: fixed [here](https://github.com/learn-co-curriculum/sinatra-password-security/commit/24d81c8bb29447ddb604abd582e9362364180377)
